[package]
name = "dusk-bls12_381-sign"
version = "0.1.0"
authors = ["Jules de Smit <julesdesmit@gmail.com>"]
edition = "2018"

[dependencies]
dusk-bls12_381 = { version = "0.8", default-features = false, features = ["groups"] }
dusk-bytes = "0.1"
rand_core = {version = "0.6"}
blake2 = {version = "0.9", default-features = false, optional = true}
libc = "0.2"

[lib]
crate-type = ["rlib", "staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
incremental = false
codegen-units = 1

[features]
default = ["std"]
std = [
    "dusk-bls12_381/default",
    "blake2",
]
