[workspace]
members = [
    "bls12_381-sign", "bls12_381-sign-ffi", "grpc-server"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
incremental = false
codegen-units = 1

